name: Dependency Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: pnpm install --frozen-lockfile
      - run: pnpm run audit
      - run: pnpm run security:scan
      - run: pnpm run sbom
