name: Security Audit

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: pnpm install --frozen-lockfile
      - run: node tools/security-audit.js
